package SEPROJ;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/* @author Harshitha */
public class OwnerPage extends javax.swing.JFrame {
    DefaultTableModel model; 
    DBclass db;
    /**
     * Creates new form OwnerPage
     */
    public OwnerPage() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        db=new DBclass();
        jPanel2.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCust = new javax.swing.JButton();
        btEmp = new javax.swing.JButton();
        btMan = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btSup = new javax.swing.JButton();
        btInv = new javax.swing.JButton();
        btLog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jNewEntry = new javax.swing.JPanel();
        tvField1 = new javax.swing.JTextField();
        tvField2 = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        tvField3 = new javax.swing.JTextField();
        jDeleteEntry = new javax.swing.JPanel();
        tvName2 = new javax.swing.JTextField();
        btRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tvdbname = new javax.swing.JLabel();
        tverror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("OWNER");

        btCust.setText("Customer Details");
        btCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCustActionPerformed(evt);
            }
        });

        btEmp.setText("Employee Details");
        btEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpActionPerformed(evt);
            }
        });

        btMan.setText("Manager Details");
        btMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManActionPerformed(evt);
            }
        });

        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btSup.setText("Supplier Details");
        btSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupActionPerformed(evt);
            }
        });

        btInv.setText("Inventory Details");
        btInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInvActionPerformed(evt);
            }
        });

        btLog.setText("Purchase Log");
        btLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
            .addComponent(btLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCust, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSup, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tvField1.setText("Name");

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNewEntryLayout = new javax.swing.GroupLayout(jNewEntry);
        jNewEntry.setLayout(jNewEntryLayout);
        jNewEntryLayout.setHorizontalGroup(
            jNewEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewEntryLayout.createSequentialGroup()
                .addGroup(jNewEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNewEntryLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jNewEntryLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jNewEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tvField1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(tvField2)
                            .addComponent(tvField3))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jNewEntryLayout.setVerticalGroup(
            jNewEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tvField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tvName2.setText("Name");

        btRemove.setText("Remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDeleteEntryLayout = new javax.swing.GroupLayout(jDeleteEntry);
        jDeleteEntry.setLayout(jDeleteEntryLayout);
        jDeleteEntryLayout.setHorizontalGroup(
            jDeleteEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDeleteEntryLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(tvName2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jDeleteEntryLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDeleteEntryLayout.setVerticalGroup(
            jDeleteEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDeleteEntryLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tvName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRemove)
                .addContainerGap())
        );

        jLabel2.setText("EDIT DATABSE OF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvdbname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jNewEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tverror, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvdbname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(tverror, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNewEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDeleteEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        new Logout().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCustActionPerformed
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(false);
        tvField1.setText("Name");
        tvField2.setText("Contact");
        tvField3.setText("INVALID");
        tvName2.setText("Name");
        db.DispCust(model, jTable1);
        tvdbname.setText("CUSTOMER");
    }//GEN-LAST:event_btCustActionPerformed

    private void btEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpActionPerformed
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(true);
        tvField1.setText("Name");
        tvField2.setText("UserId");
        tvField3.setText("Password");
        tvName2.setText("Name");
        db.DispEmp(model, jTable1);
        tvdbname.setText("EMPLOYEE");
    }//GEN-LAST:event_btEmpActionPerformed

    private void btManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManActionPerformed
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(true);
        tvField1.setText("Name");
        tvField2.setText("UserId");
        tvField3.setText("Password");
        tvName2.setText("Name");
        db.DispMang(model, jTable1);
        tvdbname.setText("MANAGER");
    }//GEN-LAST:event_btManActionPerformed

    private void btSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupActionPerformed
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(true);
        tvField1.setText("Name");
        tvField2.setText("Wares");
        tvField3.setText("Contact");
        tvName2.setText("Name");
        db.DispSup(model, jTable1);
        tvdbname.setText("SUPPLIER");
    }//GEN-LAST:event_btSupActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        tverror.setText("");
        String name= tvField1.getText();
        String field2=tvField2.getText();
        String field3=tvField3.getText();
        if(name.equals("") || field2.equals("") || field3.equals(""))
            tverror.setText("ERROR: Enter All Details");
        else
        {
            if(tvdbname.getText().equals("CUSTOMER"))
                db.addCust(name,field2,tverror);
            else if(tvdbname.getText().equals("EMPLOYEE"))
                db.addEmp(name, field2, field3);
            else if(tvdbname.getText().equals("MANAGER"))
                db.addMang(name, field2, field3);
            else if(tvdbname.getText().equals("SUPPLIER"))
                db.addSup(name, field2, field3, tverror);
            else if(tvdbname.getText().equals("INVENTORY"))
                db.addInv(name, field2, field3, tverror);
            else if(tvdbname.getText().equals("PURCHASE LOG"))
                db.addLog(name, field2, field3, tverror);
            else
                tverror.setText("AN ERROR HAS OCCURED");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        tverror.setText("");
        String namedel= tvName2.getText();
        if(namedel.equals(""))
            tverror.setText("ERROR: Enter Details");
        else
        {
            if(tvdbname.getText().equals("CUSTOMER"))
                db.delCust(namedel,tverror);
            else if(tvdbname.getText().equals("EMPLOYEE"))
                db.delEmp(namedel);        
            else if(tvdbname.getText().equals("MANAGER"))
                db.delMang(namedel);        
            else if(tvdbname.getText().equals("SUPPLIER"))
                db.delSup(namedel);        
            else if(tvdbname.getText().equals("INVENTORY"))
                db.delInv(namedel);                
            else if(tvdbname.getText().equals("PURCHASE LOG"))
                db.delLog(namedel);                
            else
                tverror.setText("AN ERROR HAS OCCURED");
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInvActionPerformed
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(true);
        tvField1.setText("Item Name");
        tvField2.setText("Quantity");
        tvField3.setText("Price");
        tvName2.setText("Item Name");
        db.DispInv(model, jTable1);
        tvdbname.setText("INVENTORY");
    }//GEN-LAST:event_btInvActionPerformed

    private void btLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogActionPerformed
        // TODO add your handling code here:
        tverror.setText("");
        jPanel2.setVisible(true);
        tvField3.setVisible(true);
        tvField1.setText("Item Name");
        tvField2.setText("Quantity");
        tvField3.setText("Price");
        tvName2.setText("Item Name");
        db.DispLog(model, jTable1);
        tvdbname.setText("PURCHASE LOG");
    }//GEN-LAST:event_btLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCust;
    private javax.swing.JButton btEmp;
    private javax.swing.JButton btInv;
    private javax.swing.JButton btLog;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btMan;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSup;
    private javax.swing.JPanel jDeleteEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jNewEntry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tvField1;
    private javax.swing.JTextField tvField2;
    private javax.swing.JTextField tvField3;
    private javax.swing.JTextField tvName2;
    private javax.swing.JLabel tvdbname;
    private javax.swing.JLabel tverror;
    // End of variables declaration//GEN-END:variables

}
